### ISSUE TITLE
Rho Emacs just halt installation process at nearly completion

### ISSUE THREAD

**Issue by duytrung** [GChristensen/rho-emacs#1]
Hi,

I have tried to install Rho emacs but it just remains un-progressed at the installation nearly completed in a very long long time. I didn't know what caused that bug.

Could you please consider to fix this problem and also provide an extractable version that could be run from the USB flash drive?

Thanks a lot

TN

**Comment by GChristensen** [comment]
fixed

**Comment by hlmbrt** [comment]
I came here via a [reddit post](https://old.reddit.com/r/emacs/comments/mav9un/rhoemacs_a_preconfigured_distribution_of_emacs/). I am experiencing the same, using [v 1.0.0 installer](https://github.com/GChristensen/rho-emacs/releases/tag/v1.0.0).

**Comment by hlmbrt** [comment]
See screenshot, after having installer open overnight:

![screen](https://i.imgur.com/W2ebpSD.png)

**Comment by GChristensen** [comment]
It is actually usable, just some third-party enhancement libraries are not compiled to elc (there are a few of them). Will think about how to prevent this.

**Comment by hlmbrt** [comment]
Thanks for checking.

In my case, once I terminate the installer process, Emacs Rho starts fine, but no emacs libraries were downloaded, so I just see a vanilla Emacs.
