### ISSUE TITLE
Bundled grep.exe causes grep to fail

### ISSUE THREAD

**Issue by petef4** [GChristensen/rho-emacs#5]
Running `M-x grep` returns no results.

Attempting to run the bundled grep.exe from the command line pops up an error dialog saying that pcre.dll was not found. `rho-emacs\utils\gnu` contains `pcre3.dll` but not `pcre.dll`. The other exe files all successfully report `--version`.

A related issue is that I needed to modify the default command line in `M-x grep` to put double quotes around `c:/Program Files/rho-emacs/utils/gnu/grep.exe` as it contains a space.

I can work around this issue by calling the Cygwin grep on my PC.

**Comment by GChristensen** [comment]
Thanks. Should be fixed in v1.0.3.

**Comment by petef4** [comment]
Thanks for the quick turn around, I confirm that v1.0.3 fixes all of the issue.

All the exe files in `rho-emacs/utils/gnu` successfully report `--version`.
