### ISSUE TITLE
Possibly upgrade to Emacs 28.2

### ISSUE THREAD

**Issue by lispstudent** [GChristensen/rho-emacs#6]
Hello,

Would it be possible to upgrade `rho-emacs` to [Emacs 28.2](http://ftp.gnu.org/gnu/emacs/windows/emacs-28/)?

Thank you for considering this.

**Comment by GChristensen** [comment]
I'll do this latter. Currently it is possible to download [this](https://gnu.mirror.constant.com/emacs/windows/emacs-28/emacs-28.2.zip) package and replace the contents of the `emacs` folder in the installation directory with it.

**Comment by lispstudent** [comment]
Thanks.

**Comment by GChristensen** [comment]
And one important thing, emacs\share\emacs\site-lisp\site-start.el file should remain from the old instalation.
