### ISSUE TITLE
About Rho calls obsolete function

### ISSUE THREAD

**Issue by petef4** [GChristensen/rho-emacs#7]
Help > About Rho gives an error `Symbol's function definition is void: toggle-read-only`. That function is obsolete since Emacs 24.3.

In `core-customization.el` `read-only-mode` should be used instead.

A secondary minor issue is that About Rho does not handle subsequent calls. Before fixing this issue the help content repeated. When the issue is worked around calling About Rho again gives `Buffer is read-only: #<buffer *About Rho*>`

**Comment by GChristensen** [comment]
Thanks. Didn't noticed switching to 29.1. That was fixed.
