### ISSUE TITLE
rhoc can't run on windows 11

### ISSUE THREAD

**Issue by QiangF** [GChristensen/rho-emacs#9]
I have got the server started in my init.el.

    (server-start)

    (defun say-hi ()
      (message "hi"))

And when I run rhoc.exe with :

    "c:/Program Files/rho-emacs/rhoc.exe" -e "(say-hi)"

I got :

     Access is denied.

And this popup error :

    This app can't run on your PC
    To find a version for your PC, check with the software publisher.

**Comment by GChristensen** [comment]
Hi, RHO already starts server, so it is necessary to do this manually. The issue happens most likely because RHO is installed in a folder with a space in the path. I'll investigate this.

**Comment by GChristensen** [comment]
I've checked, and rhoc works from a folder with spaces in the path. The error suggests that either the user has insufficient access rights to the emacs.exe or emacsclient.exe or these files are damaged, or the path is incorrect. It worth to check if they are could be launched by the same user account as rhoc.
